<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sensors" nsURI="http:///ca/gc/space/mrt/sensors/model/sensors.ecore"
    nsPrefix="ca.gc.space.mrt.sensors">
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="../../ca.gc.space.topology.core/model/topology.ecore#//AggregateGroupNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//SensorStatus"
        transient="true" defaultValueLiteral="OFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SensorStatus">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents the various states that a sensor could be in.&#xA;&#xA;Typical status transitions :&#xA;&#xA;Power up (nominal) : OFF -> BUSY (initialization) -> READY &#xA;Power up (off-nominal) : OFF -> BUSY (initialization) -> FAILED &#xA;&#xA;Data acquition (nominal): READY -> BUSY (Acquisition) -> READY&#xA;Data acquition (off-nominal): READY -> BUSY (Acquisition) -> FAILED&#xA;"/>
    </eAnnotations>
    <eLiterals name="OFF"/>
    <eLiterals name="READY" value="1"/>
    <eLiterals name="BUSY" value="2"/>
    <eLiterals name="FAILED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Referenceable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceFrame" eType="ecore:EClass ../../ca.gc.space.topology.core/model/topology.ecore#//Node"/>
  </eClassifiers>
</ecore:EPackage>
