/**
 *
 * $Id: CartesianPolygonValidator.java,v 1.1.6.2 2015/05/21 15:50:48 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data3d.validation;

import javax.vecmath.Vector3d;

import ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinates;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data3d.CartesianPolygon}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CartesianPolygonValidator {
	boolean validate();

	boolean validateSurface(double value);
	boolean validateNormal(Vector3d value);
	boolean validateCentroid(CartesianPositionCoordinates value);
}
