/**
 *
 * $Id: CartesianOrientationCoordinatesValidator.java,v 1.1.6.2 2015/05/21 15:50:48 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data3d.validation;


/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data3d.CartesianOrientationCoordinates}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CartesianOrientationCoordinatesValidator {
	boolean validate();

	boolean validateXRotation(double value);
	boolean validateYRotation(double value);
	boolean validateZRotation(double value);
}
