/**
 *
 * $Id: PointNormalLocatorValidator.java,v 1.1.6.2 2015/05/21 15:50:48 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data3d.validation;

import ca.gc.space.mrt.geometry.data3d.NormalPointCloud;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data3d.PointNormalLocator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PointNormalLocatorValidator {
	boolean validate();

	boolean validateDataSet(NormalPointCloud value);
}
