/**
 *
 * $Id: VoxelBased3DPointCloudResamplerValidator.java,v 1.1.6.2 2015/05/21 15:50:48 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data3d.validation;


/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data3d.VoxelBased3DPointCloudResampler}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VoxelBased3DPointCloudResamplerValidator {
	boolean validate();

	boolean validateResolutionX(double value);
	boolean validateResolutionY(double value);
	boolean validateResolutionZ(double value);
	boolean validateMinimumNumberOfPointPerVoxel(int value);
	boolean validateTileResolution(double value);
}
