<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sim" nsURI="http:///ca/gc/space/mrt/sensors/gps/sim.ecore" nsPrefix="ca.gc.space.mrt.sensors.gps">
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedConnection" eSuperTypes="platform:/plugin/ca.gc.space.mrt.sensors.gps/model/GPS.ecore#//GPSConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedDataInterpreter" eSuperTypes="platform:/plugin/ca.gc.space.mrt.sensors.gps/model/GPS.ecore#//GPSDataInterpreter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateFrequency" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1000">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delay, in milliseconds before updateGPS() returns."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLatitude" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startLongitude" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitudeIncrement" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.000001"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitudeIncrement" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.000001"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimFacade">
    <eOperations name="createSimulatedGPS" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.sensors.gps/model/GPS.ecore#//MarkedGPS">
      <eParameters name="initialLatitude" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="initialLongitude" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="marker" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//PositionMarker"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
