/**
 * <copyright>
 * </copyright>
 *
 * $Id: RecordingsExporterValidator.java,v 1.2.4.2 2015/05/21 15:51:13 pallard Exp $
 */
package ca.gc.space.mrt.common.recorders.validation;

import ca.gc.space.mrt.common.recorders.Recordings;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.common.recorders.RecordingsExporter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RecordingsExporterValidator {
	boolean validate();

	boolean validateRecordings(Recordings value);
}
