/**
 * Canadian Space Agency 2007.
 *
 * $Id: Data3dItemProviderAdapterFactory.java,v 1.3.4.3 2015/08/13 14:22:45 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data3d.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import ca.gc.space.mrt.geometry.data3d.util.Data3dAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Data3dItemProviderAdapterFactory extends Data3dAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Canadian Space Agency 2008.";

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Data3dItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianPositionCoordinatesItemProvider cartesianPositionCoordinatesItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianPositionCoordinatesAdapter() {
		if (cartesianPositionCoordinatesItemProvider == null) {
			cartesianPositionCoordinatesItemProvider = new CartesianPositionCoordinatesItemProvider(this);
		}

		return cartesianPositionCoordinatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.RGBCartesianPositionCoordinates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RGBCartesianPositionCoordinatesItemProvider rgbCartesianPositionCoordinatesItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.RGBCartesianPositionCoordinates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRGBCartesianPositionCoordinatesAdapter() {
		if (rgbCartesianPositionCoordinatesItemProvider == null) {
			rgbCartesianPositionCoordinatesItemProvider = new RGBCartesianPositionCoordinatesItemProvider(this);
		}

		return rgbCartesianPositionCoordinatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianOrientationCoordinates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianOrientationCoordinatesItemProvider cartesianOrientationCoordinatesItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianOrientationCoordinates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianOrientationCoordinatesAdapter() {
		if (cartesianOrientationCoordinatesItemProvider == null) {
			cartesianOrientationCoordinatesItemProvider = new CartesianOrientationCoordinatesItemProvider(this);
		}

		return cartesianOrientationCoordinatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianPolygon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianPolygonItemProvider cartesianPolygonItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianPolygon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianPolygonAdapter() {
		if (cartesianPolygonItemProvider == null) {
			cartesianPolygonItemProvider = new CartesianPolygonItemProvider(this);
		}

		return cartesianPolygonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesSetItemProvider cartesianCoordinatesSetItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesSetAdapter() {
		if (cartesianCoordinatesSetItemProvider == null) {
			cartesianCoordinatesSetItemProvider = new CartesianCoordinatesSetItemProvider(this);
		}

		return cartesianCoordinatesSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMesh} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesMeshItemProvider cartesianCoordinatesMeshItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMesh}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesMeshAdapter() {
		if (cartesianCoordinatesMeshItemProvider == null) {
			cartesianCoordinatesMeshItemProvider = new CartesianCoordinatesMeshItemProvider(this);
		}

		return cartesianCoordinatesMeshItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMesh} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianTriangularMeshItemProvider cartesianTriangularMeshItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMesh}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianTriangularMeshAdapter() {
		if (cartesianTriangularMeshItemProvider == null) {
			cartesianTriangularMeshItemProvider = new CartesianTriangularMeshItemProvider(this);
		}

		return cartesianTriangularMeshItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphericalCoordinates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphericalCoordinatesItemProvider sphericalCoordinatesItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphericalCoordinates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphericalCoordinatesAdapter() {
		if (sphericalCoordinatesItemProvider == null) {
			sphericalCoordinatesItemProvider = new SphericalCoordinatesItemProvider(this);
		}

		return sphericalCoordinatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphericalCoordinatesSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphericalCoordinatesSetItemProvider sphericalCoordinatesSetItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphericalCoordinatesSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphericalCoordinatesSetAdapter() {
		if (sphericalCoordinatesSetItemProvider == null) {
			sphericalCoordinatesSetItemProvider = new SphericalCoordinatesSetItemProvider(this);
		}

		return sphericalCoordinatesSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphericalPolygon} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphericalPolygonItemProvider sphericalPolygonItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphericalPolygon}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphericalPolygonAdapter() {
		if (sphericalPolygonItemProvider == null) {
			sphericalPolygonItemProvider = new SphericalPolygonItemProvider(this);
		}

		return sphericalPolygonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphericalTriangle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphericalTriangleItemProvider sphericalTriangleItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphericalTriangle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphericalTriangleAdapter() {
		if (sphericalTriangleItemProvider == null) {
			sphericalTriangleItemProvider = new SphericalTriangleItemProvider(this);
		}

		return sphericalTriangleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SpericalCoordinatesMesh} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpericalCoordinatesMeshItemProvider spericalCoordinatesMeshItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SpericalCoordinatesMesh}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpericalCoordinatesMeshAdapter() {
		if (spericalCoordinatesMeshItemProvider == null) {
			spericalCoordinatesMeshItemProvider = new SpericalCoordinatesMeshItemProvider(this);
		}

		return spericalCoordinatesMeshItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphericalTriangularMesh} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphericalTriangularMeshItemProvider sphericalTriangularMeshItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphericalTriangularMesh}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphericalTriangularMeshAdapter() {
		if (sphericalTriangularMeshItemProvider == null) {
			sphericalTriangularMeshItemProvider = new SphericalTriangularMeshItemProvider(this);
		}

		return sphericalTriangularMeshItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.Pose} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PoseItemProvider poseItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.Pose}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPoseAdapter() {
		if (poseItemProvider == null) {
			poseItemProvider = new PoseItemProvider(this);
		}

		return poseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.SphereSamplingShape} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SphereSamplingShapeItemProvider sphereSamplingShapeItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.SphereSamplingShape}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSphereSamplingShapeAdapter()
	{
		if (sphereSamplingShapeItemProvider == null) {
			sphereSamplingShapeItemProvider = new SphereSamplingShapeItemProvider(this);
		}

		return sphereSamplingShapeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSetShapeSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesSetShapeSamplerItemProvider cartesianCoordinatesSetShapeSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSetShapeSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesSetShapeSamplerAdapter() {
		if (cartesianCoordinatesSetShapeSamplerItemProvider == null) {
			cartesianCoordinatesSetShapeSamplerItemProvider = new CartesianCoordinatesSetShapeSamplerItemProvider(this);
		}

		return cartesianCoordinatesSetShapeSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMeshSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesMeshSamplerItemProvider cartesianCoordinatesMeshSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMeshSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesMeshSamplerAdapter() {
		if (cartesianCoordinatesMeshSamplerItemProvider == null) {
			cartesianCoordinatesMeshSamplerItemProvider = new CartesianCoordinatesMeshSamplerItemProvider(this);
		}

		return cartesianCoordinatesMeshSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMeshPolygonSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesMeshPolygonSamplerItemProvider cartesianCoordinatesMeshPolygonSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMeshPolygonSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesMeshPolygonSamplerAdapter()
	{
		if (cartesianCoordinatesMeshPolygonSamplerItemProvider == null) {
			cartesianCoordinatesMeshPolygonSamplerItemProvider = new CartesianCoordinatesMeshPolygonSamplerItemProvider(this);
		}

		return cartesianCoordinatesMeshPolygonSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMeshSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianTriangularMeshSamplerItemProvider cartesianTriangularMeshSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMeshSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianTriangularMeshSamplerAdapter()
	{
		if (cartesianTriangularMeshSamplerItemProvider == null) {
			cartesianTriangularMeshSamplerItemProvider = new CartesianTriangularMeshSamplerItemProvider(this);
		}

		return cartesianTriangularMeshSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMeshPolygonSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianTriangularMeshPolygonSamplerItemProvider cartesianTriangularMeshPolygonSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangularMeshPolygonSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianTriangularMeshPolygonSamplerAdapter()
	{
		if (cartesianTriangularMeshPolygonSamplerItemProvider == null) {
			cartesianTriangularMeshPolygonSamplerItemProvider = new CartesianTriangularMeshPolygonSamplerItemProvider(this);
		}

		return cartesianTriangularMeshPolygonSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.Data3dFacade} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Data3dFacadeItemProvider data3dFacadeItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.Data3dFacade}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createData3dFacadeAdapter() {
		if (data3dFacadeItemProvider == null) {
			data3dFacadeItemProvider = new Data3dFacadeItemProvider(this);
		}

		return data3dFacadeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianTriangleItemProvider cartesianTriangleItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianTriangle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianTriangleAdapter() {
		if (cartesianTriangleItemProvider == null) {
			cartesianTriangleItemProvider = new CartesianTriangleItemProvider(this);
		}

		return cartesianTriangleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.Data3DIO} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Data3DIOItemProvider data3DIOItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.Data3DIO}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createData3DIOAdapter() {
		if (data3DIOItemProvider == null) {
			data3DIOItemProvider = new Data3DIOItemProvider(this);
		}

		return data3DIOItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.PointLocator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PointLocatorItemProvider pointLocatorItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.PointLocator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPointLocatorAdapter() {
		if (pointLocatorItemProvider == null) {
			pointLocatorItemProvider = new PointLocatorItemProvider(this);
		}

		return pointLocatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.Data3DUtils} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Data3DUtilsItemProvider data3DUtilsItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.Data3DUtils}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createData3DUtilsAdapter() {
		if (data3DUtilsItemProvider == null) {
			data3DUtilsItemProvider = new Data3DUtilsItemProvider(this);
		}

		return data3DUtilsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.NormalPointCloud} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NormalPointCloudItemProvider normalPointCloudItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.NormalPointCloud}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNormalPointCloudAdapter() {
		if (normalPointCloudItemProvider == null) {
			normalPointCloudItemProvider = new NormalPointCloudItemProvider(this);
		}

		return normalPointCloudItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.VecmathKdTreePointLocator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VecmathKdTreePointLocatorItemProvider vecmathKdTreePointLocatorItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.VecmathKdTreePointLocator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVecmathKdTreePointLocatorAdapter() {
		if (vecmathKdTreePointLocatorItemProvider == null) {
			vecmathKdTreePointLocatorItemProvider = new VecmathKdTreePointLocatorItemProvider(this);
		}

		return vecmathKdTreePointLocatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.MeshLocaliser} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeshLocaliserItemProvider meshLocaliserItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.MeshLocaliser}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeshLocaliserAdapter() {
		if (meshLocaliserItemProvider == null) {
			meshLocaliserItemProvider = new MeshLocaliserItemProvider(this);
		}

		return meshLocaliserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.PointNormalLocator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PointNormalLocatorItemProvider pointNormalLocatorItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.PointNormalLocator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPointNormalLocatorAdapter() {
		if (pointNormalLocatorItemProvider == null) {
			pointNormalLocatorItemProvider = new PointNormalLocatorItemProvider(this);
		}

		return pointNormalLocatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.DelaunayMesher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DelaunayMesherItemProvider delaunayMesherItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.DelaunayMesher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDelaunayMesherAdapter() {
		if (delaunayMesherItemProvider == null) {
			delaunayMesherItemProvider = new DelaunayMesherItemProvider(this);
		}

		return delaunayMesherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMapMesher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DigitalElevationMapMesherItemProvider digitalElevationMapMesherItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMapMesher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDigitalElevationMapMesherAdapter() {
		if (digitalElevationMapMesherItemProvider == null) {
			digitalElevationMapMesherItemProvider = new DigitalElevationMapMesherItemProvider(this);
		}

		return digitalElevationMapMesherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMapSampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DigitalElevationMapSamplerItemProvider digitalElevationMapSamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMapSampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDigitalElevationMapSamplerAdapter() {
		if (digitalElevationMapSamplerItemProvider == null) {
			digitalElevationMapSamplerItemProvider = new DigitalElevationMapSamplerItemProvider(this);
		}

		return digitalElevationMapSamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.TriangularMeshNormalsCalculator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriangularMeshNormalsCalculatorItemProvider triangularMeshNormalsCalculatorItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.TriangularMeshNormalsCalculator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriangularMeshNormalsCalculatorAdapter() {
		if (triangularMeshNormalsCalculatorItemProvider == null) {
			triangularMeshNormalsCalculatorItemProvider = new TriangularMeshNormalsCalculatorItemProvider(this);
		}

		return triangularMeshNormalsCalculatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.TriangularMesh2NormalPointCloud} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriangularMesh2NormalPointCloudItemProvider triangularMesh2NormalPointCloudItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.TriangularMesh2NormalPointCloud}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriangularMesh2NormalPointCloudAdapter() {
		if (triangularMesh2NormalPointCloudItemProvider == null) {
			triangularMesh2NormalPointCloudItemProvider = new TriangularMesh2NormalPointCloudItemProvider(this);
		}

		return triangularMesh2NormalPointCloudItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.PointsRangeGager} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PointsRangeGagerItemProvider pointsRangeGagerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.PointsRangeGager}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPointsRangeGagerAdapter() {
		if (pointsRangeGagerItemProvider == null) {
			pointsRangeGagerItemProvider = new PointsRangeGagerItemProvider(this);
		}

		return pointsRangeGagerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.UniquePointsFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UniquePointsFilterItemProvider uniquePointsFilterItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.UniquePointsFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUniquePointsFilterAdapter() {
		if (uniquePointsFilterItemProvider == null) {
			uniquePointsFilterItemProvider = new UniquePointsFilterItemProvider(this);
		}

		return uniquePointsFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.TriangleEdgeLenghtTriangularMeshFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriangleEdgeLenghtTriangularMeshFilterItemProvider triangleEdgeLenghtTriangularMeshFilterItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.TriangleEdgeLenghtTriangularMeshFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriangleEdgeLenghtTriangularMeshFilterAdapter() {
		if (triangleEdgeLenghtTriangularMeshFilterItemProvider == null) {
			triangleEdgeLenghtTriangularMeshFilterItemProvider = new TriangleEdgeLenghtTriangularMeshFilterItemProvider(this);
		}

		return triangleEdgeLenghtTriangularMeshFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.OutlierFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutlierFilterItemProvider outlierFilterItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.OutlierFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutlierFilterAdapter() {
		if (outlierFilterItemProvider == null) {
			outlierFilterItemProvider = new OutlierFilterItemProvider(this);
		}

		return outlierFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.RasterPointCloud} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RasterPointCloudItemProvider rasterPointCloudItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.RasterPointCloud}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRasterPointCloudAdapter() {
		if (rasterPointCloudItemProvider == null) {
			rasterPointCloudItemProvider = new RasterPointCloudItemProvider(this);
		}

		return rasterPointCloudItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.RasterPointCloudToCartesianCoordinatesSet} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RasterPointCloudToCartesianCoordinatesSetItemProvider rasterPointCloudToCartesianCoordinatesSetItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.RasterPointCloudToCartesianCoordinatesSet}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRasterPointCloudToCartesianCoordinatesSetAdapter() {
		if (rasterPointCloudToCartesianCoordinatesSetItemProvider == null) {
			rasterPointCloudToCartesianCoordinatesSetItemProvider = new RasterPointCloudToCartesianCoordinatesSetItemProvider(this);
		}

		return rasterPointCloudToCartesianCoordinatesSetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.VoxelBased3DPointCloudResampler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VoxelBased3DPointCloudResamplerItemProvider voxelBased3DPointCloudResamplerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.VoxelBased3DPointCloudResampler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVoxelBased3DPointCloudResamplerAdapter() {
		if (voxelBased3DPointCloudResamplerItemProvider == null) {
			voxelBased3DPointCloudResamplerItemProvider = new VoxelBased3DPointCloudResamplerItemProvider(this);
		}

		return voxelBased3DPointCloudResamplerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.RigidBodyPoseTracker} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RigidBodyPoseTrackerItemProvider rigidBodyPoseTrackerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.RigidBodyPoseTracker}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRigidBodyPoseTrackerAdapter() {
		if (rigidBodyPoseTrackerItemProvider == null) {
			rigidBodyPoseTrackerItemProvider = new RigidBodyPoseTrackerItemProvider(this);
		}

		return rigidBodyPoseTrackerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.PositionMarker} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PositionMarkerItemProvider positionMarkerItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.PositionMarker}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPositionMarkerAdapter() {
		if (positionMarkerItemProvider == null) {
			positionMarkerItemProvider = new PositionMarkerItemProvider(this);
		}

		return positionMarkerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CubeSamplingShape} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CubeSamplingShapeItemProvider cubeSamplingShapeItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CubeSamplingShape}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCubeSamplingShapeAdapter() {
		if (cubeSamplingShapeItemProvider == null) {
			cubeSamplingShapeItemProvider = new CubeSamplingShapeItemProvider(this);
		}

		return cubeSamplingShapeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSetExtent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianCoordinatesSetExtentItemProvider cartesianCoordinatesSetExtentItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesSetExtent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianCoordinatesSetExtentAdapter() {
		if (cartesianCoordinatesSetExtentItemProvider == null) {
			cartesianCoordinatesSetExtentItemProvider = new CartesianCoordinatesSetExtentItemProvider(this);
		}

		return cartesianCoordinatesSetExtentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DigitalElevationMapItemProvider digitalElevationMapItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.DigitalElevationMap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDigitalElevationMapAdapter() {
		if (digitalElevationMapItemProvider == null) {
			digitalElevationMapItemProvider = new DigitalElevationMapItemProvider(this);
		}

		return digitalElevationMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinatesMesher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CartesianPositionCoordinatesMesherItemProvider cartesianPositionCoordinatesMesherItemProvider;

	/**
	 * This creates an adapter for a {@link ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinatesMesher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCartesianPositionCoordinatesMesherAdapter()
	{
		if (cartesianPositionCoordinatesMesherItemProvider == null) {
			cartesianPositionCoordinatesMesherItemProvider = new CartesianPositionCoordinatesMesherItemProvider(this);
		}

		return cartesianPositionCoordinatesMesherItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (cartesianPolygonItemProvider != null) cartesianPolygonItemProvider.dispose();
		if (cartesianTriangleItemProvider != null) cartesianTriangleItemProvider.dispose();
		if (sphericalPolygonItemProvider != null) sphericalPolygonItemProvider.dispose();
		if (sphericalTriangleItemProvider != null) sphericalTriangleItemProvider.dispose();
		if (cartesianPositionCoordinatesItemProvider != null) cartesianPositionCoordinatesItemProvider.dispose();
		if (rgbCartesianPositionCoordinatesItemProvider != null) rgbCartesianPositionCoordinatesItemProvider.dispose();
		if (cartesianOrientationCoordinatesItemProvider != null) cartesianOrientationCoordinatesItemProvider.dispose();
		if (cartesianCoordinatesSetItemProvider != null) cartesianCoordinatesSetItemProvider.dispose();
		if (digitalElevationMapItemProvider != null) digitalElevationMapItemProvider.dispose();
		if (cartesianCoordinatesMeshItemProvider != null) cartesianCoordinatesMeshItemProvider.dispose();
		if (cartesianTriangularMeshItemProvider != null) cartesianTriangularMeshItemProvider.dispose();
		if (sphericalCoordinatesItemProvider != null) sphericalCoordinatesItemProvider.dispose();
		if (sphericalCoordinatesSetItemProvider != null) sphericalCoordinatesSetItemProvider.dispose();
		if (spericalCoordinatesMeshItemProvider != null) spericalCoordinatesMeshItemProvider.dispose();
		if (sphericalTriangularMeshItemProvider != null) sphericalTriangularMeshItemProvider.dispose();
		if (poseItemProvider != null) poseItemProvider.dispose();
		if (sphereSamplingShapeItemProvider != null) sphereSamplingShapeItemProvider.dispose();
		if (cartesianCoordinatesSetShapeSamplerItemProvider != null) cartesianCoordinatesSetShapeSamplerItemProvider.dispose();
		if (cartesianCoordinatesMeshSamplerItemProvider != null) cartesianCoordinatesMeshSamplerItemProvider.dispose();
		if (cartesianCoordinatesMeshPolygonSamplerItemProvider != null) cartesianCoordinatesMeshPolygonSamplerItemProvider.dispose();
		if (cartesianTriangularMeshSamplerItemProvider != null) cartesianTriangularMeshSamplerItemProvider.dispose();
		if (cartesianTriangularMeshPolygonSamplerItemProvider != null) cartesianTriangularMeshPolygonSamplerItemProvider.dispose();
		if (cartesianPositionCoordinatesMesherItemProvider != null) cartesianPositionCoordinatesMesherItemProvider.dispose();
		if (data3dFacadeItemProvider != null) data3dFacadeItemProvider.dispose();
		if (data3DIOItemProvider != null) data3DIOItemProvider.dispose();
		if (pointLocatorItemProvider != null) pointLocatorItemProvider.dispose();
		if (data3DUtilsItemProvider != null) data3DUtilsItemProvider.dispose();
		if (normalPointCloudItemProvider != null) normalPointCloudItemProvider.dispose();
		if (vecmathKdTreePointLocatorItemProvider != null) vecmathKdTreePointLocatorItemProvider.dispose();
		if (meshLocaliserItemProvider != null) meshLocaliserItemProvider.dispose();
		if (pointNormalLocatorItemProvider != null) pointNormalLocatorItemProvider.dispose();
		if (delaunayMesherItemProvider != null) delaunayMesherItemProvider.dispose();
		if (digitalElevationMapMesherItemProvider != null) digitalElevationMapMesherItemProvider.dispose();
		if (digitalElevationMapSamplerItemProvider != null) digitalElevationMapSamplerItemProvider.dispose();
		if (triangularMeshNormalsCalculatorItemProvider != null) triangularMeshNormalsCalculatorItemProvider.dispose();
		if (triangularMesh2NormalPointCloudItemProvider != null) triangularMesh2NormalPointCloudItemProvider.dispose();
		if (pointsRangeGagerItemProvider != null) pointsRangeGagerItemProvider.dispose();
		if (uniquePointsFilterItemProvider != null) uniquePointsFilterItemProvider.dispose();
		if (triangleEdgeLenghtTriangularMeshFilterItemProvider != null) triangleEdgeLenghtTriangularMeshFilterItemProvider.dispose();
		if (outlierFilterItemProvider != null) outlierFilterItemProvider.dispose();
		if (rasterPointCloudItemProvider != null) rasterPointCloudItemProvider.dispose();
		if (rasterPointCloudToCartesianCoordinatesSetItemProvider != null) rasterPointCloudToCartesianCoordinatesSetItemProvider.dispose();
		if (voxelBased3DPointCloudResamplerItemProvider != null) voxelBased3DPointCloudResamplerItemProvider.dispose();
		if (rigidBodyPoseTrackerItemProvider != null) rigidBodyPoseTrackerItemProvider.dispose();
		if (positionMarkerItemProvider != null) positionMarkerItemProvider.dispose();
		if (cubeSamplingShapeItemProvider != null) cubeSamplingShapeItemProvider.dispose();
		if (cartesianCoordinatesSetExtentItemProvider != null) cartesianCoordinatesSetExtentItemProvider.dispose();
	}

}
