/**
 *
 */
package org.eclipse.symphony.common.images.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.symphony.common.images.AbstractEImage;

/**
 * A sample validator interface for {@link org.eclipse.symphony.common.images.ImagesAlbum}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImagesAlbumValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateImages(EList<AbstractEImage> value);
}
