/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.mobility.controllers.validation;

import ca.gc.asc_csa.apogy.addons.geometry.paths.Path;

import ca.gc.asc_csa.apogy.addons.mobility.controllers.PathRecorderSamplingMode;

import ca.gc.asc_csa.apogy.addons.sensors.pose.PoseSensor;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.mobility.controllers.PathRecorder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PathRecorderValidator {
	boolean validate();

	boolean validatePositionSensor(PoseSensor value);
	boolean validateMinimumDistanceDelta(double value);
	boolean validateMinimumTimeDelta(double value);
	boolean validateSamplingMode(PathRecorderSamplingMode value);
	boolean validateRecordedPath(Path value);
}
