/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.mobility.controllers.validation;

import ca.gc.asc_csa.apogy.addons.geometry.paths.Path;

import ca.gc.asc_csa.apogy.addons.mobility.MobilePlatform;

import ca.gc.asc_csa.apogy.addons.mobility.controllers.PathFollowerState;

import ca.gc.asc_csa.apogy.addons.sensors.pose.PoseSensor;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.mobility.controllers.PathFollower}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PathFollowerValidator {
	boolean validate();

	boolean validatePath(Path value);
	boolean validatePlatform(MobilePlatform value);
	boolean validatePoseSensor(PoseSensor value);
	boolean validateDestinationReached(boolean value);
	boolean validatePathFollowerState(PathFollowerState value);
}
