/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.common.geometry.data3d.validation;

import java.util.List;

import javax.vecmath.Point3d;
import javax.vecmath.Vector3d;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.common.geometry.data3d.NormalPointCloud}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NormalPointCloudValidator {
	boolean validate();

	boolean validatePoints(List<Point3d> value);
	boolean validateNormals(List<Vector3d> value);
}
