/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.validation;

import ca.gc.asc_csa.apogy.common.math.Matrix4x4;

import ca.gc.asc_csa.apogy.common.topology.Node;

import ca.gc.asc_csa.apogy.core.ApogySystem;
import ca.gc.asc_csa.apogy.core.ConnectionPoint;

import ca.gc.asc_csa.apogy.core.invocator.TypeMember;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.AssemblyLink}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssemblyLinkValidator {
	boolean validate();

	boolean validateParentTypeMember(TypeMember value);
	boolean validateSubSystemTypeMember(TypeMember value);
	boolean validateParentConnectionPoint(ConnectionPoint value);
	boolean validateTransformationMatrix(Matrix4x4 value);
	boolean validateGeometryNode(Node value);
	boolean validateParentInstance(ApogySystem value);
	boolean validateSubSystemInstance(ApogySystem value);
}
