/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.validation;

import ca.gc.asc_csa.apogy.common.emf.TimeSource;

import ca.gc.asc_csa.apogy.core.ApogyEnvironment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.TimeSourcesList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeSourcesListValidator {
	boolean validate();

	boolean validateEnvironment(ApogyEnvironment value);
	boolean validateTimeSources(EList<TimeSource> value);
}
