/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.ui.validation;

import ca.gc.asc_csa.apogy.common.images.AbstractEImage;

import ca.gc.asc_csa.apogy.core.environment.ImageMapLayerPresentation;
import ca.gc.asc_csa.apogy.core.environment.RectangularRegion;

import ca.gc.asc_csa.apogy.core.environment.ui.MapAnnotation;

import javax.vecmath.Color3f;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.ui.MapViewConfiguration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapViewConfigurationValidator {
	boolean validate();

	boolean validateMapLayers(EList<ImageMapLayerPresentation> value);
	boolean validateBackgroundColor(Color3f value);
	boolean validateMapAnnotations(EList<MapAnnotation> value);
	boolean validateDefaultRectangularRegion(RectangularRegion value);
	boolean validateMapImage(AbstractEImage value);
	boolean validateMapImageRectangularRegion(RectangularRegion value);
	boolean validateExtent(RectangularRegion value);
}
