/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.validation;

import ca.gc.asc_csa.apogy.common.images.AbstractEImage;

import ca.gc.asc_csa.apogy.core.environment.CartesianTriangularMeshMapLayerNode;
import ca.gc.asc_csa.apogy.core.environment.MapLayerPresentation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.CartesianTriangularMeshMapLayer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CartesianTriangularMeshMapLayerValidator {
	boolean validate();

	boolean validateMeshIsDirty(boolean value);
	boolean validateMapLayerPresentations(EList<MapLayerPresentation> value);
	boolean validateTextureImage(AbstractEImage value);
	boolean validateCartesianTriangularMeshMapLayerNode(CartesianTriangularMeshMapLayerNode value);
}
