/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.validation;

import ca.gc.asc_csa.apogy.common.math.Matrix4x4;

import javax.vecmath.Color3f;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.LineOfSightImageMapLayer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LineOfSightImageMapLayerValidator {
	boolean validate();

	boolean validateLineOfSightAvailableColor(Color3f value);
	boolean validateLineOfSightNotAvailableColor(Color3f value);
	boolean validateObserverPose(Matrix4x4 value);
	boolean validateTargetHeightAboveGround(double value);
	boolean validateUseHeightPerpendicularToGround(boolean value);
}
