/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.common.topology.addons.primitives.validation;

import ca.gc.asc_csa.apogy.common.math.Tuple3d;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.common.topology.addons.primitives.DirectionalLight}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DirectionalLightValidator {
	boolean validate();

	boolean validateDirection(Tuple3d value);
}
