/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.common.topology.addons.primitives.validation;

import ca.gc.asc_csa.apogy.common.topology.Node;

import javax.vecmath.Point3d;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.common.topology.addons.primitives.PickVector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PickVectorValidator {
	boolean validate();

	boolean validateIntersectionDistance(double value);
	boolean validateIntersectedNode(Node value);
	boolean validateRelativeIntersectionPosition(Point3d value);
	boolean validateAbsoluteIntersectionPosition(Point3d value);
	boolean validateNodeTypesInIntersection(EList<EClass> value);
	boolean validateNodeTypesToExcludeFromIntersection(EList<EClass> value);
}
