<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editor_dependency"
    nsURI="http://editor_dependency/1.0" nsPrefix="editor_dependency">
  <eClassifiers xsi:type="ecore:EClass" name="workspace.editor" eSuperTypes="#//core.editor"/>
  <eClassifiers xsi:type="ecore:EClass" name="workspace.ui" eSuperTypes="#//core.editor #//workspace.editor"/>
  <eClassifiers xsi:type="ecore:EClass" name="core.editor"/>
</ecore:EPackage>
