/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.examples.rover.validation;

import ca.gc.asc_csa.apogy.examples.camera.PTUCamera;

import ca.gc.asc_csa.apogy.examples.mobile_platform.MobilePlatform;

import ca.gc.asc_csa.apogy.examples.robotic_arm.RoboticArm;

import ca.gc.asc_csa.apogy.examples.rover.PowerSystem;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.examples.rover.Rover}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoverValidator {
	boolean validate();

	boolean validateRoboticArm(RoboticArm value);
	boolean validateMobilePlatform(MobilePlatform value);
	boolean validateArmCamera(PTUCamera value);
	boolean validateCenterCamera(PTUCamera value);
	boolean validatePowerSystem(PowerSystem value);
	boolean validateLinearVelocity(double value);
	boolean validateAngularVelocity(double value);
	boolean validateInitialized(boolean value);
	boolean validateDisposed(boolean value);
}
