<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fov" nsURI="http:///ca/gc/space/mrt/sensors/fov/model/fov.ecore"
    nsPrefix="ca.gc.space.mrt.sensors.fov">
  <eClassifiers xsi:type="ecore:EClass" name="FieldOfView" eSuperTypes="platform:/plugin/ca.gc.space.topology.core/model/topology.ecore#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="DistanceRange">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines an distance range by specifying a minimum and maximum distance."/>
    </eAnnotations>
    <eOperations name="isWithinRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns whether or not the specified distance falls within the range."/>
      </eAnnotations>
      <eParameters name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumDistance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumDistance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngularSpan">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines an angular span by specifying a maximum and a minimum angle (in radians)."/>
    </eAnnotations>
    <eOperations name="isWithinRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns whether or not the specified angle (in radians) falls within the angular range."/>
      </eAnnotations>
      <eParameters name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumAngle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumAngle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spanningAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The total angular span, in radians."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="centerAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The center of the angular span, in radians."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RectangularFrustrumFieldOfView" eSuperTypes="#//FieldOfView">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A field of view that has a frustrum shape. This frustrum has a rectangular base and is right (its axis is perpendicular to both bases). See http://en.wikipedia.org/wiki/Frustrum."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="#//DistanceRange"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontalFieldOfViewAngle"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Total horizontal field of view, in radians."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verticalFieldOfViewAngle"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Total vertical field of view, in radians."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="0.0" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The volume of the contained within the field of view."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConicalFieldOfView" eSuperTypes="#//FieldOfView">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A conical field of view defined by its apex angle."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfViewAngle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The apex angle of the conical field of view."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="#//DistanceRange"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="0.0" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The volume of the contained within the field of view."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CircularSectorFieldOfView" eSuperTypes="#//FieldOfView">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A field of view shaped like a circular sector (see http://en.wikipedia.org/wiki/Circular_sector).&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angularSpan" lowerBound="1"
        eType="#//AngularSpan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//DistanceRange"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="0.0"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The area of the circular sector."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FOVFacade">
    <eOperations name="createDistanceRange" eType="#//DistanceRange">
      <eParameters name="minimumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createDistanceRange" eType="#//DistanceRange">
      <eParameters name="distanceRange" eType="#//DistanceRange"/>
    </eOperations>
    <eOperations name="createAngularSpan" eType="#//AngularSpan">
      <eParameters name="minimumAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createAngularSpan" eType="#//AngularSpan">
      <eParameters name="angularSpan" eType="#//AngularSpan"/>
    </eOperations>
    <eOperations name="createRectangularFrustrumFieldOfView" eType="#//RectangularFrustrumFieldOfView">
      <eParameters name="minimumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="horizontalFieldOfViewAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="verticalFieldOfViewAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createRectangularFrustrumFieldOfView" eType="#//RectangularFrustrumFieldOfView">
      <eParameters name="rectangularFrustrumFieldOfView" eType="#//RectangularFrustrumFieldOfView"/>
    </eOperations>
    <eOperations name="createConicalFieldOfView" eType="#//ConicalFieldOfView">
      <eParameters name="minimumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="fieldOfViewAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createConicalFieldOfView" eType="#//ConicalFieldOfView">
      <eParameters name="conicalFieldOfView" eType="#//ConicalFieldOfView"/>
    </eOperations>
    <eOperations name="createCircularSectorFieldOfView" eType="#//CircularSectorFieldOfView">
      <eParameters name="minimumAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="minimumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="maximumDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createCircularSectorFieldOfView" eType="#//CircularSectorFieldOfView">
      <eParameters name="circularSectorFieldOfView" eType="#//CircularSectorFieldOfView"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RectangularFrustrumFieldOfViewSamplingShape">
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPolygon"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transform" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.math.core/model/Math.ecore#//Matrix4x4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rectangularFrustrumFieldOfView"
        eType="#//RectangularFrustrumFieldOfView"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSamplingShape">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//PolygonSamplingShape">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
      <eTypeArguments eTypeParameter="#//RectangularFrustrumFieldOfViewSamplingShape/PolygonType"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
