/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.topology.validation;

import ca.gc.asc_csa.apogy.core.ResultsListNode;
import ca.gc.asc_csa.apogy.core.environment.ApogyEnvironment;
import ca.gc.asc_csa.apogy.core.environment.WorksiteNode;
import ca.gc.asc_csa.apogy.core.topology.ApogySystemAPIsNode;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.topology.ApogyEnvironmentNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApogyEnvironmentNodeValidator {
	boolean validate();

	boolean validateApogyEnvironment(ApogyEnvironment value);
	boolean validateWorksiteNode(WorksiteNode value);
	boolean validateResultsListNode(ResultsListNode value);
	boolean validateApogySystemAPIsNode(ApogySystemAPIsNode value);
}
