/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.examples.lander.validation;

import javax.vecmath.Matrix3d;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.examples.lander.Position}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PositionValidator {
	boolean validate();

	boolean validateX(double value);
	boolean validateY(double value);
	boolean validateZ(double value);
	boolean validateAttitude(Matrix3d value);
}
