/**
 *
 * $Id: CircularExclusionZoneValidator.java,v 1.1.8.2 2015/05/21 15:50:53 pallard Exp $
 */
package ca.gc.space.mrt.mobility.pathplanners.validation;


/**
 * A sample validator interface for {@link ca.gc.space.mrt.mobility.pathplanners.CircularExclusionZone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CircularExclusionZoneValidator {
	boolean validate();

	boolean validateRadius(double value);
	boolean validateInvertSamplingShape(boolean value);
}
