/**
 * <copyright>
 * </copyright>
 *
 * $Id: MeshWayPointPathPlannerValidator.java,v 1.2.4.2 2015/05/21 15:50:53 pallard Exp $
 */
package ca.gc.space.mrt.mobility.pathplanners.validation;

import org.eclipse.symphony.common.geometry.data.Mesh;

import ca.gc.space.mrt.geometry.data3d.CartesianCoordinatesMesh;
import ca.gc.space.mrt.geometry.data3d.CartesianPolygon;
import ca.gc.space.mrt.geometry.data3d.CartesianPositionCoordinates;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.mobility.pathplanners.MeshWayPointPathPlanner}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MeshWayPointPathPlannerValidator {
	boolean validate();

	boolean validateMesh(Mesh<CartesianPositionCoordinates, CartesianPolygon> value);

	boolean validateMesh(CartesianCoordinatesMesh value);
}
