/**
 * <copyright>
 * </copyright>
 *
 * $Id: CoordinatesSet25DValidator.java,v 1.2.4.2 2015/05/21 15:51:19 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data25d.validation;

import org.eclipse.emf.common.util.EList;

import ca.gc.space.mrt.geometry.data25d.Coordinates25D;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data25d.CoordinatesSet25D}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoordinatesSet25DValidator {
	boolean validate();

	boolean validateCoordinates25D(EList<Coordinates25D> value);
}
