/**
 * <copyright>
 * </copyright>
 *
 * $Id: SphericalCoordinatesSet25D2VtpExporterValidator.java,v 1.2.4.2 2015/05/21 15:51:20 pallard Exp $
 */
package ca.gc.space.mrt.geometry.data25d.validation;


/**
 * A sample validator interface for {@link ca.gc.space.mrt.geometry.data25d.SphericalCoordinatesSet25D2VtpExporter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SphericalCoordinatesSet25D2VtpExporterValidator {
	boolean validate();

}
