/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.orbit.earth.ui.validation;

import ca.gc.asc_csa.apogy.common.emf.Timed;

import ca.gc.asc_csa.apogy.core.environment.orbit.OrbitModel;

import ca.gc.asc_csa.apogy.core.environment.orbit.earth.SpacecraftSwathCorridor;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.orbit.earth.ui.SpacecraftSwathWorldWindLayer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpacecraftSwathWorldWindLayerValidator {
	boolean validate();

	boolean validateOrbitModel(OrbitModel value);
	boolean validateTimeSource(Timed value);
	boolean validateForwardPropagationDuration(double value);
	boolean validateBackwardPropagationDuration(double value);
	boolean validateTimeInterval(double value);
	boolean validateLeftSwathAngle(double value);
	boolean validateRightSwathAngle(double value);
	boolean validateShowGroundTrace(boolean value);
	boolean validateForwardSpacecraftSwathCorridor(SpacecraftSwathCorridor value);
	boolean validateBackwardSpacecraftSwathCorridor(SpacecraftSwathCorridor value);
}
