<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="controllers" nsURI="http:///ca/gc/space/mrt/mobility/controllers/model/controllers.ecore"
    nsPrefix="ca.gc.space.mrt.mobility">
  <eClassifiers xsi:type="ecore:EClass" name="PathFollower">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A PathFollower is an entity that makes a MobilePlatform follow a specified Path.&#xA;&#xA;The default implementation of PathFollower listens for changes in the SensorStatus of its PoseSensor and the MobilePlateformStatus of its MobilePlateform and pauses or resumes the path following accordingly."/>
    </eAnnotations>
    <eTypeParameters name="PlatformType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.mobility/model/mobility.ecore#//MobilePlateform"/>
    </eTypeParameters>
    <eTypeParameters name="PathType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//Path"/>
    </eTypeParameters>
    <eOperations name="start" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="pause" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="resume" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="stop" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="isTransitionValid" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="state" eType="#//PathFollowerState"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path">
      <eGenericType eTypeParameter="#//PathFollower/PathType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform">
      <eGenericType eTypeParameter="#//PathFollower/PlatformType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poseSensor" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.sensors.pose/model/pose.ecore#//PoseSensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationReached" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathFollowerState" eType="#//PathFollowerState"
        defaultValueLiteral="IDLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PathFollowerState">
    <eLiterals name="IDLE" literal="IDLE"/>
    <eLiterals name="RUNNING" value="1"/>
    <eLiterals name="PAUSED" value="2"/>
    <eLiterals name="FAILED" value="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkidSteeredPlatformPathFollower">
    <eTypeParameters name="PlateformType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.mobility/model/mobility.ecore#//SkidSteeredMobilePlateform"/>
    </eTypeParameters>
    <eTypeParameters name="PathType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//Path"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumAngularVelocity"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumLinearVelocity"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eGenericSuperTypes eClassifier="#//PathFollower">
      <eTypeArguments eTypeParameter="#//SkidSteeredPlatformPathFollower/PlateformType"/>
      <eTypeArguments eTypeParameter="#//SkidSteeredPlatformPathFollower/PathType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathRecorder">
    <eTypeParameters name="PathType">
      <eBounds eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//Path"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionSensor" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.sensors.pose/model/pose.ecore#//PoseSensor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumDistanceDelta" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumTimeDelta" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplingMode" eType="#//PathRecorderSamplingMode"
        defaultValueLiteral="ON_DISTANCE_DELTA"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recordedPath">
      <eGenericType eTypeParameter="#//PathRecorder/PathType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaypointPathRecorder">
    <eGenericSuperTypes eClassifier="#//PathRecorder">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//WayPointPath"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PathRecorderSamplingMode">
    <eLiterals name="ON_DISTANCE_DELTA"/>
    <eLiterals name="ON_TIME_DELTA" value="1"/>
    <eLiterals name="ON_TIME_OR_DISTANCE_DELTA" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkidSteeredWayPointPathFollower">
    <eGenericSuperTypes eClassifier="#//PathFollower">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.mobility/model/mobility.ecore#//SkidSteeredMobilePlateform"/>
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//WayPointPath"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AstolfiGuidanceController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentWayPoint" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousWayPoint" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentPoseInGuidanceReferenceFrame"
        eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//Pose"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rho" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phi" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yaw" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nu" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omega" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="krho" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kphi" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kalpha" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationDistanceThreshold"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wayPointDistanceThreshold"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kHill" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hillThreshold" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phiThresholdForReducedVelocity"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alphaThresholdForReducedVelocity"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smoothPathEnabled" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eGenericSuperTypes eClassifier="#//SkidSteeredPlatformPathFollower">
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.mobility/model/mobility.ecore#//SkidSteeredMobilePlateform"/>
      <eTypeArguments eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.paths/model/paths.ecore#//WayPointPath"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
