<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bindings" nsURI="http://ca/gc/asc_csa/jinput/bindings/1.0" nsPrefix="ca.gc.asc_csa.jinput.bindings">
  <eAnnotations source="EAnnotation0"/>
  <eClassifiers xsi:type="ecore:EClass" name="PollingTask">
    <eOperations name="startAcquiring"/>
    <eOperations name="stopAcquiring"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
        eType="#//Binding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="ecore:EClass platform:/plugin/ca.gc.asc_csa.jinput/model/jinput_emf.ecore#//EController"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding">
    <eOperations name="executeBinding"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//MethodParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="button" eType="ecore:EClass platform:/plugin/ca.gc.asc_csa.jinput/model/jinput_emf.ecore#//EComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="converter" eType="#//Converter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Converter" abstract="true">
    <eOperations name="convert" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="from" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
