/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.validation;

import ca.gc.asc_csa.apogy.addons.Ruler3dToolNode;

import javax.vecmath.Color3f;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.Ruler3DTool}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Ruler3DToolValidator {
	boolean validate();

	boolean validateRulerColor(Color3f value);
	boolean validateExtremitiesRadius(double value);
	boolean validateMinorTickColor(Color3f value);
	boolean validateMinorTickSpacing(double value);
	boolean validateMinorTickLength(double value);
	boolean validateMajorTickColor(Color3f value);
	boolean validateMajorTickSpacing(double value);
	boolean validateMajorTickLength(double value);
	boolean validateRuler3dToolNode(Ruler3dToolNode value);
}
