<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="math" nsURI="http:///ca/gc/space/math.ecore" nsPrefix="ca.gc.space">
  <eClassifiers xsi:type="ecore:EClass" name="Matrix4x4">
    <eOperations name="asMatrix4d" eType="#//Matrix4d"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m00" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m01" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m02" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m03" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m10" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m11" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m13" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m20" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m21" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m22" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m23" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m30" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m31" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m32" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m33" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathFacade">
    <eOperations name="createMatrix4x4" eType="#//Matrix4x4">
      <eParameters name="matrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="createMatrix3x3" eType="#//Matrix3x3">
      <eParameters name="matrix" eType="#//Matrix3d"/>
    </eOperations>
    <eOperations name="createTuple3d" eType="#//Tuple3d">
      <eParameters name="tuple" eType="#//VecmathTuple3d"/>
    </eOperations>
    <eOperations name="createTuple3d" eType="#//Tuple3d">
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createPolynomial" eType="#//Polynomial">
      <eParameters name="coeffs" eType="#//EDoubleArray">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The coefficients of the polynomial, sorted in increasing order.&#xA;coeffs[n-1]*x^n-1 + coeffs[n-2]*x^n-2 + ... + coeffs[0]"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="createIdentityMatrix4x4" eType="#//Matrix4x4"/>
    <eOperations name="createIdentityMatrix3x3" eType="#//Matrix3x3"/>
    <eOperations name="extractPosition" eType="#//Tuple3d">
      <eParameters name="matrix" eType="#//Matrix4x4"/>
    </eOperations>
    <eOperations name="extractOrientation" eType="#//Tuple3d">
      <eParameters name="matrix" eType="#//Matrix4x4"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix3x3">
    <eOperations name="asMatrix3d" eType="#//Matrix3d"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m00" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m01" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m02" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m10" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m11" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m20" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m21" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="m22" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tuple3d">
    <eOperations name="asTuple3d" eType="#//VecmathTuple3d"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polynomial">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coeffs" eType="#//EDoubleArray">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The coefficients of the polynomial, sorted in increasing order.&#xA;coeffs[n-1]*x^n-1 + coeffs[n-2]*x^n-2 + ... + coeffs[0].&#xA;&#xA;For instance: polynomial 3*x^2 + 5*x + 2, the coefficients would be:&#xA;coeffs = { 2, 5, 3 }."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realRoots" eType="#//EDoubleArray"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imaginaryRoots" eType="#//EDoubleArray"
        changeable="false" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathIO">
    <eOperations name="readTrMatrix" eType="#//Matrix4x4" eExceptions="#//Exception">
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="writeTrMatrix" eExceptions="#//Exception">
      <eParameters name="trMatrix" eType="#//Matrix4x4"/>
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="writeTrMatrix" eExceptions="#//Exception">
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDoubleArray" instanceClassName="double[]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Matrix3d" instanceClassName="javax.vecmath.Matrix3d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Matrix4d" instanceClassName="javax.vecmath.Matrix4d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="VecmathTuple3d" instanceClassName="javax.vecmath.Tuple3d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
</ecore:EPackage>
