/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.sensors.gps.validation;

import ca.gc.asc_csa.apogy.addons.sensors.gps.MarkedGPS;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.sensors.gps.GPSPoseSensor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GPSPoseSensorValidator {
	boolean validate();

	boolean validateGps(EList<MarkedGPS> value);
	boolean validateOriginLatitude(double value);
	boolean validateOriginLongitude(double value);
	boolean validateNeAngle(double value);
	boolean validateOriginElevation(double value);
	boolean validateMaxInitTime(long value);
}
