/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.sensors.gps.validation;

import ca.gc.asc_csa.apogy.addons.sensors.gps.GPSQuality;

import java.util.Date;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.sensors.gps.GPSReading}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GPSReadingValidator {
	boolean validate();

	boolean validateLatitude(double value);
	boolean validateLongitude(double value);
	boolean validateElevation(double value);
	boolean validateQuality(GPSQuality value);
	boolean validateTimeStamp(Date value);
	boolean validateNumberOfSatellites(int value);
	boolean validateHorizontalDilutionPos(double value);
	boolean validateMeanSeaLevel(double value);
	boolean validateCheckSum(int value);
}
