<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="property" nsURI="http:///ca/gc/space/eclipse/emf/ui/property.ecore"
    nsPrefix="ca.gc.space.eclipse.emf.ui.property">
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCellEditorContributor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellEditorProvider" eType="#//PropertyCellEditorProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCellEditorContributors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//PropertyCellEditorContributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCellViewerContentContributor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellViewerContentProvider"
        eType="#//PropertyCellViewerContentProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyCellViewerContentContributors">
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" upperBound="-1" eType="#//PropertyCellViewerContentContributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PropertyCellEditorProvider" instanceClassName="ca.gc.space.eclipse.emf.ui.property.PropertyCellEditorProvider"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PropertyCellViewerContentProvider"
      instanceClassName="ca.gc.space.eclipse.emf.ui.property.PropertyCellViewerContentProvider"/>
</ecore:EPackage>
