/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.addons.sensors.range.validation;

import ca.gc.asc_csa.apogy.common.geometry.data3d.CartesianTriangularMesh;

import ca.gc.asc_csa.apogy.common.topology.ContentNode;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.addons.sensors.range.RangeScannerSimulator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RangeScannerSimulatorValidator {
	boolean validate();

	boolean validateMeshNode(ContentNode<CartesianTriangularMesh> value);
	boolean validateNoiseEnabled(boolean value);
	boolean validateTimeCroppingMesh(long value);
	boolean validateTimeFindingIntersections(long value);
	boolean validateTimeGettingSimulatedRays(long value);
}
