/**
 *
 * $Id: PrimitivesFacadeValidator.java,v 1.1.6.3 2015/02/03 20:01:31 rlarcheveque Exp $
 */
package ca.gc.space.topology.core.primitives.validation;


/**
 * A sample validator interface for {@link ca.gc.space.topology.core.primitives.PrimitivesFacade}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PrimitivesFacadeValidator {
	boolean validate();

}
