<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pathplanners" nsURI="http:///ca/gc/space/mrt/pathplanners/pathplanners.ecore"
    nsPrefix="ca.gc.space.mrt.pathplanners">
  <eClassifiers xsi:type="ecore:EClass" name="WayPointPathPlanner">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A path planner that produces a WayPoinPath."/>
    </eAnnotations>
    <eOperations name="plan" lowerBound="1" eType="ecore:EClass ../../ca.gc.space.mrt.geometry.paths/model/paths.ecore#//WayPointPath"
        eExceptions="ecore:EDataType ../../org.eclipse.symphony.common.processors/model/processors.ecore#//Exception">
      <eParameters name="currentPosition" lowerBound="1" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
      <eParameters name="destinationPosition" lowerBound="1" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentDestination" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentPosition" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"
        transient="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="ecore:EClass ../../ca.gc.space.mrt.geometry.paths/model/paths.ecore#//WayPointPath"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeshWayPointPathPlanner" eSuperTypes="#//WayPointPathPlanner">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A path planner that produces a WayPoinPath based on a triangular mesh."/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPolygon"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mesh" transient="true">
      <eGenericType eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Mesh">
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
        <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPolygon"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusionZone" abstract="true" eSuperTypes="../../ca.gc.space.topology.core/model/topology.ecore#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represent a zone to be excluded from trajectory generated by path planners that support exclusion zones."/>
    </eAnnotations>
    <eOperations name="isInside" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="point" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eOperations>
    <eOperations name="intersects" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="from" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
      <eParameters name="to" eType="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CircularExclusionZone">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represent an exclusion zone defined as a circle. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The radius of the exclusion zone."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invertSamplingShape" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eGenericSuperTypes eClassifier="#//ExclusionZone"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSamplingShape">
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//PolygonSamplingShape">
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.symphony.common.geometry.data3d/model/data3d.ecore#//CartesianTriangle"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathPlannersFacade">
    <eOperations name="createCircularExclusionZone" eType="#//CircularExclusionZone">
      <eParameters name="radius" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="parent" eType="ecore:EClass ../../ca.gc.space.topology.core/model/topology.ecore#//GroupNode"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
