/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.orbit.earth.validation;

import java.util.Date;

import ca.gc.asc_csa.apogy.core.environment.earth.EarthSurfaceLocation;
import ca.gc.asc_csa.apogy.core.environment.orbit.earth.EarthOrbitModel;
import ca.gc.asc_csa.apogy.core.environment.orbit.earth.VisibilityPassSpacecraftPositionHistory;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.orbit.earth.VisibilityPass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VisibilityPassValidator {
	boolean validate();

	boolean validateOrbitModel(EarthOrbitModel value);
	boolean validateSurfaceLocation(EarthSurfaceLocation value);
	boolean validateStartTime(Date value);
	boolean validateEndTime(Date value);
	boolean validatePositionHistory(VisibilityPassSpacecraftPositionHistory value);
	boolean validateDuration(double value);
}
