<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mobility" nsURI="http:///ca/gc/space/mrt/mobility/model/mobility.ecore"
    nsPrefix="ca.gc.space.mrt">
  <eClassifiers xsi:type="ecore:EClass" name="MobilePlateform" eSuperTypes="../../org.eclipse.symphony.common.topology.core/model/topology.ecore#//AggregateGroupNode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a generic mobile plateform."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moving" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobilePlateformStatus"
        eType="#//MobilePlateformStatus" defaultValueLiteral="OFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkidSteeredMobilePlateform" eSuperTypes="#//MobilePlateform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandedRightWheelsVelocity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualRightWheelsVelocity"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandedLeftWheelsVelocity"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualLeftWheelsVelocity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandedAngularVelocity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualAngularVelocity"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandedTranslationVelocity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualTranslationVelocity"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveSteeringWidth"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MobilePlateformStatus">
    <eLiterals name="OFF"/>
    <eLiterals name="READY" value="1"/>
    <eLiterals name="BUSY" value="2"/>
    <eLiterals name="FAILED" value="3"/>
  </eClassifiers>
</ecore:EPackage>
