<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.example.org/ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="OperationCall"/>
  <eClassifiers xsi:type="ecore:EClass" name="Program" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationcall" upperBound="-1"
        eType="#//OperationCall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleProgram" eSuperTypes="#//ScriptBasedProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllersProgram" eSuperTypes="#//Program"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaScriptProgram" eSuperTypes="#//ScriptBasedProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="LuaProgram" eSuperTypes="#//ScriptBasedProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptBasedProgram" abstract="true"
      eSuperTypes="#//Program"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachineProgram" eSuperTypes="#//GraphicalBasedProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttProgram" eSuperTypes="#//GraphicalBasedProgram"/>
  <eClassifiers xsi:type="ecore:EClass" name="GraphicalBasedProgram" abstract="true"
      eSuperTypes="#//Program"/>
</ecore:EPackage>
