/**
 * <copyright>
 * </copyright>
 *
 * $Id: ReferenceableValidator.java,v 1.2.4.2 2015/05/21 15:49:36 pallard Exp $
 */
package ca.gc.space.mrt.sensors.sensors.validation;

import ca.gc.space.topology.Node;


/**
 * A sample validator interface for {@link ca.gc.space.mrt.sensors.sensors.Referenceable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceableValidator {
	boolean validate();

	boolean validateReferenceFrame(Node value);

	boolean validateReferenceFrame(Object value);
}
