package org.eclipse.symphony.core.environment.ui.preferences;


public class SymphonyEnvironmentUIPreferencesConstants 
{
	public static final String DEFAULT_MAP_VIEW_CONFIGURATION_X_MIN_ID = "DEFAULT_MAP_VIEW_CONFIGURATION_X_MIN_ID";
	public static final double DEFAULT_MAP_VIEW_CONFIGURATION_X_MIN = -20.0;
		
	public static final String DEFAULT_MAP_VIEW_CONFIGURATION_X_MAX_ID = "DEFAULT_MAP_VIEW_CONFIGURATION_X_MAX_ID";
	public static final double DEFAULT_MAP_VIEW_CONFIGURATION_X_MAX = 20.0;

	public static final String DEFAULT_MAP_VIEW_CONFIGURATION_Y_MIN_ID = "DEFAULT_MAP_VIEW_CONFIGURATION_Y_MIN_ID";
	public static final double DEFAULT_MAP_VIEW_CONFIGURATION_Y_MIN = -20.0;
		
	public static final String DEFAULT_MAP_VIEW_CONFIGURATION_Y_MAX_ID = "DEFAULT_MAP_VIEW_CONFIGURATION_Y_MAX_ID";
	public static final double DEFAULT_MAP_VIEW_CONFIGURATION_Y_MAX = 20.0;	
	
	public static final String DEFAULT_MAP_VIEW_UPDATE_PERIOD_MILLISECONDS_ID = "DEFAULT_MAP_VIEW_UPDATE_PERIOD_MILLISECONDS_ID";
	public static final long DEFAULT_MAP_VIEW_UPDATE_PERIOD_MILLISECONDS = 1000;
	
	public static final String DEFAULT_MAP_VIEW_IMAGE_MAXIMUM_NUMBER_OF_PIXELS_ID = "DEFAULT_MAP_VIEW_IMAGE_MAXIMUM_NUMBER_OF_PIXELS_ID";
	public static final int DEFAULT_MAP_VIEW_IMAGE_MAXIMUM_NUMBER_OF_PIXELS = 1024 * 1024;

	public static final String DEFAULT_STAR_MAGNITUDE_CUTOFF_ID = "DEFAULT_STAR_MAGNITUDE_CUTOFF_ID";
	public static final double DEFAULT_STAR_MAGNITUDE_CUTOFF = 6.0;
	
	
	// Earth Surface Worksite Settings.
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_AXIS_LENGHT_ID = "DEFAULT_EARTH_SURFACE_WORSITE_AXIS_LENGHT_ID";
	public static final double DEFAULT_EARTH_SURFACE_WORKSITE_AXIS_LENGHT = 5.0;

	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_AXIS_VISIBLE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_AXIS_VISIBLE_ID";
	public static final boolean DEFAULT_EARTH_SURFACE_WORKSITE_AXIS_VISIBLE = true;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_AZIMUTH_VISIBLE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_AZIMUTH_VISIBLE_ID";
	public static final boolean DEFAULT_EARTH_SURFACE_WORKSITE_AZIMUTH_VISIBLE = true;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_AZIMUTH_LINES_VISIBLE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_AZIMUTH_LINES_VISIBLE_ID";
	public static final boolean DEFAULT_EARTH_SURFACE_WORKSITE_AZIMUTH_LINES_VISIBLE = true;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_ELEVATION_LINES_VISIBLE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_ELEVATION_LINES_VISIBLE_ID";
	public static final boolean DEFAULT_EARTH_SURFACE_WORKSITE_ELEVATION_LINES_VISIBLE = true;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_VISIBLE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_PLANE_VISIBLE_ID";
	public static final boolean DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_VISIBLE = true;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_GRID_SIZE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_PLANE_GRID_SIZE_ID";
	public static final double DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_GRID_SIZE = 1.0;
	
	public static final String DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_SIZE_ID = "DEFAULT_EARTH_SURFACE_WORSITE_PLANE_SIZE_ID";
	public static final double DEFAULT_EARTH_SURFACE_WORKSITE_PLANE_SIZE = 20.0;

	
}
