<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pose" nsURI="http:///ca/gc/space/mrt/sensors/pose/model/pose.ecore"
    nsPrefix="ca.gc.space.mrt.sensors">
  <eClassifiers xsi:type="ecore:EClass" name="PositionSensor" eSuperTypes="platform:/plugin/ca.gc.space.topology.core/model/topology.ecore#//PositionNode #//SelfPlaceSensor">
    <eOperations name="resetPosition" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eParameters name="newPosition" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionCoordinates" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//CartesianPositionCoordinates"
        changeable="false" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrientationSensor" eSuperTypes="platform:/plugin/ca.gc.space.topology.core/model/topology.ecore#//RotationNode #//SelfPlaceSensor">
    <eOperations name="resetOrientation" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eParameters name="newOrientation" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//CartesianOrientationCoordinates"/>
    </eOperations>
    <eOperations name="extractOrientationFromMatrix" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//CartesianOrientationCoordinates">
      <eParameters name="matrix" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.math.core/model/Math.ecore#//Matrix3x3"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orientationCoordinates"
        eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//CartesianOrientationCoordinates"
        changeable="false" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PoseSensor" eSuperTypes="platform:/plugin/ca.gc.space.topology.core/model/topology.ecore#//TransformNode #//PositionSensor #//OrientationSensor">
    <eOperations name="resetPose" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eParameters name="newPose" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//Pose"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pose" lowerBound="1" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//Pose"
        changeable="false" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataLogger" eType="#//PoseDataLogger"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelfPlaceSensor" eSuperTypes="platform:/plugin/ca.gc.space.mrt.sensors/model/sensors.ecore#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedPositionSensor" eSuperTypes="#//PositionSensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatePeriod" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedOrientationSensor" eSuperTypes="#//OrientationSensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatePeriod" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulatedPoseSensor" eSuperTypes="#//PoseSensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatePeriod" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zAngularVelocity" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PoseDataLogger" abstract="true" interface="true">
    <eOperations name="logPose" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//IOException">
      <eParameters name="pose" eType="ecore:EClass platform:/plugin/ca.gc.space.mrt.geometry.data3d/model/data3d.ecore#//Pose"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputFile" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSVDataLogger" eSuperTypes="#//PoseDataLogger"/>
  <eClassifiers xsi:type="ecore:EClass" name="PoseFacade">
    <eOperations name="createCSVDataLogger" eType="#//CSVDataLogger">
      <eParameters name="fileName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InertialMeasurementUnit" eSuperTypes="#//OrientationSensor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="angularVelocity" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.math.core/model/Math.ecore#//Tuple3d"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linearAcceleration" eType="ecore:EClass platform:/plugin/org.eclipse.symphony.common.math.core/model/Math.ecore#//Tuple3d"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
