/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.environment.orbit.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.environment.orbit.ValidityRangeProvider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValidityRangeProviderValidator {
	boolean validate();

	boolean validateFromValidDate(Date value);
	boolean validateToValidDate(Date value);
}
