<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://ca/gc/asc_csa/eclipse/images/core/1.0" nsPrefix="ca.gc.asc_csa.eclipse.images">
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ImageData" instanceClassName="org.eclipse.swt.graphics.ImageData"/>
  <eClassifiers xsi:type="ecore:EDataType" name="BufferedImage" instanceClassName="java.awt.image.BufferedImage"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="java.awt.Color"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Font" instanceClassName="java.awt.Font"/>
  <eClassifiers xsi:type="ecore:EClass" name="EImage" eSuperTypes="#//AbstractEImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageContent" eType="#//BufferedImage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImagesAlbum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="images" upperBound="-1"
        eType="#//AbstractEImage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEImage" abstract="true" interface="true">
    <eOperations name="asBufferedImage" eType="#//BufferedImage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URLEImage" eSuperTypes="#//AbstractEImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EImagesUtilities">
    <eOperations name="copy" eType="#//AbstractEImage">
      <eParameters name="originalImage" lowerBound="1" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="convertToGrayScale" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="resize" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="scaleFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="resize" eType="#//AbstractEImage">
      <eParameters name="originalImage" lowerBound="1" eType="#//AbstractEImage"/>
      <eParameters name="widthScaleFactor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="heightScaleFactor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="resize" eType="#//AbstractEImage">
      <eParameters name="originalImage" lowerBound="1" eType="#//AbstractEImage"/>
      <eParameters name="newWidth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="newHeight" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="createTransparentImage" eType="#//AbstractEImage">
      <eParameters name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="height" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="saveImageAsJPEG" eExceptions="#//Exception">
      <eParameters name="destinationFilePath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="image" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="saveImageAsPNG" eExceptions="#//Exception">
      <eParameters name="destinationFilePath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="image" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="applyOverlay" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="overlayImage" eType="#//AbstractEImage"/>
      <eParameters name="allowOverlayResize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="flipHorizontal" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="flipVertical" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="rotate" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="angle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="enableImageResize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="translate" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="widthTranslation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="heightTranslation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getAllEncompassingImageSize" eType="#//ImageSize">
      <eParameters name="images">
        <eGenericType eClassifier="#//List">
          <eTypeArguments>
            <eUpperBound eClassifier="#//AbstractEImage"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="superPoseImages" eType="#//AbstractEImage">
      <eParameters name="images">
        <eGenericType eClassifier="#//List">
          <eTypeArguments>
            <eUpperBound eClassifier="#//AbstractEImage"/>
          </eTypeArguments>
        </eGenericType>
      </eParameters>
      <eParameters name="allowImageResize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="alignment" eType="#//ImageAlignment"/>
    </eOperations>
    <eOperations name="superPoseImages" eType="#//AbstractEImage">
      <eParameters name="imageA" eType="#//AbstractEImage"/>
      <eParameters name="imageB" eType="#//AbstractEImage"/>
      <eParameters name="allowImageResize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="alignment" eType="#//ImageAlignment"/>
    </eOperations>
    <eOperations name="addBorder" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="borderWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getSubImage" eType="#//AbstractEImage" eExceptions="#//Exception">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gets a sub image from a specified image. Note that the widthOffset and heightOffset are relative to the upper left corner of the image."/>
      </eAnnotations>
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="widthOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="heightOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="subImageWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="subImageHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="convertToBufferedImage" eType="#//BufferedImage">
      <eParameters name="imageData" eType="#//ImageData"/>
    </eOperations>
    <eOperations name="convertToImageData" eType="#//ImageData">
      <eParameters name="bufferedImage" eType="#//BufferedImage"/>
    </eOperations>
    <eOperations name="createUniformColorImage" eType="#//AbstractEImage">
      <eParameters name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="height" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="applyAlpha" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="applyEdgeFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="applyContrastAndBrightnessFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="contrast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="brightness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="applyExposureFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="exposure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="applyInvertFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
    </eOperations>
    <eOperations name="applyRescaleFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="applyGainFilter" eType="#//AbstractEImage">
      <eParameters name="originalImage" eType="#//AbstractEImage"/>
      <eParameters name="gain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="bias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createTextImage" eType="#//AbstractEImage">
      <eParameters name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="font" eType="#//Font"/>
      <eParameters name="textColor" eType="#//Color"/>
      <eParameters name="backgroundColor" eType="#//Color"/>
      <eParameters name="borderWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageSize">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEImageProvider" abstract="true"
      interface="true">
    <eOperations name="getAbstractEImage" eType="#//AbstractEImage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImageAlignment">
    <eLiterals name="CENTER" value="1"/>
    <eLiterals name="LOWER_LEFT_CORNER" value="2"/>
    <eLiterals name="UPPER_LEFT_CORNER" value="3"/>
    <eLiterals name="LOWER_RIGHT_CORNER" value="4"/>
    <eLiterals name="UPPER_RIGHT_CORNER" value="5"/>
  </eClassifiers>
</ecore:EPackage>
