/**
 *
 * $Id: VectorValidator.java,v 1.1.6.3 2015/02/03 20:01:31 rlarcheveque Exp $
 */
package org.eclipse.symphony.common.topology.addons.primitives.validation;

import javax.vecmath.Point3d;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link org.eclipse.symphony.common.topology.addons.primitives.Vector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VectorValidator {
	boolean validate();

	boolean validateXRotation(double value);
	boolean validateYRotation(double value);
	boolean validateZRotation(double value);
	boolean validateLength(double value);
	boolean validateEndPoint(Point3d value);
	boolean validateIntersectionDistance(double value);

	boolean validateNodeTypesIncludedinIntersection(EList<EClass> value);
}
