/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.invocator.validation;

import ca.gc.asc_csa.apogy.core.invocator.DataProductsListsContainer;
import ca.gc.asc_csa.apogy.core.invocator.InvocatorSession;
import ca.gc.asc_csa.apogy.core.invocator.OperationCallResultsList;
import ca.gc.asc_csa.apogy.core.invocator.RecordingResultsList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.invocator.DataProductsList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataProductsListValidator {
	boolean validate();

	boolean validateDataProductsListsContainer(DataProductsListsContainer value);
	boolean validateOperationCallResultsList(OperationCallResultsList value);
	boolean validateRecordingResultsList(RecordingResultsList value);
	boolean validateInvocatorSession(InvocatorSession value);
}
