/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.core.invocator.validation;

import ca.gc.asc_csa.apogy.common.emf.TreeRootNode;

import ca.gc.asc_csa.apogy.core.invocator.TypeMemberReferenceTreeElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.core.invocator.TypeMemberReferenceTreeElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypeMemberReferenceTreeElementValidator {
	boolean validate();

	boolean validateChild(EList<TypeMemberReferenceTreeElement> value);
	boolean validateParent(TypeMemberReferenceTreeElement value);
	boolean validateFeatureRootNode(TreeRootNode value);
	boolean validateRoot(boolean value);
	boolean validateRootElement(TypeMemberReferenceTreeElement value);
	boolean validateLeaf(boolean value);
}
