/**
 * <copyright>
 * </copyright>
 *
 * $Id: CsvColumnValidator.java,v 1.2.4.2 2015/05/21 15:49:55 pallard Exp $
 */
package ca.gc.space.mrt.common.csv.validation;

import java.util.Map.Entry;

/**
 * A sample validator interface for {@link ca.gc.space.mrt.common.csv.CsvColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CsvColumnValidator {
	boolean validate();

	boolean validateValues(Entry value);
	boolean validateDescription(String value);
	boolean validateName(String value);
}
