<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data3d" nsURI="http:///ca/gc/space/mrt/geometry/data3d.ecore"
    nsPrefix="ca.gc.space.mrt.geometry">
  <eClassifiers xsi:type="ecore:EClass" name="CartesianPolygon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surface" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="normal" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centroid" lowerBound="1"
        eType="#//CartesianPositionCoordinates" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Polygon">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianTriangle" eSuperTypes="#//CartesianPolygon"/>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalPolygon">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Polygon">
      <eTypeArguments eClassifier="#//SphericalCoordinates"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalTriangle" eSuperTypes="#//SphericalPolygon"/>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianPositionCoordinates" eSuperTypes="platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Coordinates">
    <eOperations name="asPoint3d" eType="#//Point3d"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RGBCartesianPositionCoordinates" eSuperTypes="#//CartesianPositionCoordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianOrientationCoordinates" eSuperTypes="platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Coordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xRotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yRotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zRotation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesSet">
    <eOperations name="getExtent" eType="#//CartesianCoordinatesSetExtent"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSet">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalElevationMap" eSuperTypes="#//CartesianCoordinatesSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimension" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimension" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesMesh">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Mesh">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianPolygon"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CartesianCoordinatesSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianTriangularMesh">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Mesh">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianTriangle"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//CartesianCoordinatesSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalCoordinates" eSuperTypes="platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Coordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalCoordinatesSet">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSet">
      <eTypeArguments eClassifier="#//SphericalCoordinates"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpericalCoordinatesMesh">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Mesh">
      <eTypeArguments eClassifier="#//SphericalCoordinates"/>
      <eTypeArguments eClassifier="#//SphericalPolygon"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//SphericalCoordinatesSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SphericalTriangularMesh">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Mesh">
      <eTypeArguments eClassifier="#//SphericalCoordinates"/>
      <eTypeArguments eClassifier="#//SphericalTriangle"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//SphericalCoordinatesSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pose" eSuperTypes="#//CartesianPositionCoordinates #//CartesianOrientationCoordinates"/>
  <eClassifiers xsi:type="ecore:EClass" name="SphereSamplingShape">
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//CartesianPolygon"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="center" eType="#//CartesianPositionCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeJustTouching" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSamplingShape">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//PolygonSamplingShape">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eTypeParameter="#//SphereSamplingShape/PolygonType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesSetShapeSampler">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSetShapesSampler">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesMeshSampler">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//MeshCoordinatesShapesSampler">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianPolygon"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesMeshPolygonSampler">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//MeshPolygonShapesSampler">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianPolygon"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianTriangularMeshSampler">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//MeshCoordinatesShapesSampler">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianTriangle"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianTriangularMeshPolygonSampler">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//MeshPolygonShapesSampler">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eClassifier="#//CartesianTriangle"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianPositionCoordinatesMesher">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data3dFacade">
    <eOperations name="createCartesianPositionCoordinates" eType="#//CartesianPositionCoordinates">
      <eParameters name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="z" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createCartesianOrientationCoordinates" eType="#//CartesianOrientationCoordinates">
      <eParameters name="xRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="yRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="zRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createSphericalCoordinates" eType="#//SphericalCoordinates">
      <eParameters name="phi" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="theta" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="r" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createPose" eType="#//Pose">
      <eParameters name="x" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="y" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="z" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="xRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="yRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="zRotation" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="createPose" eType="#//Pose">
      <eParameters name="pose" eType="#//Pose"/>
    </eOperations>
    <eOperations name="createPose" eType="#//Pose">
      <eParameters name="position" eType="#//CartesianPositionCoordinates"/>
      <eParameters name="orientation" eType="#//CartesianOrientationCoordinates"/>
    </eOperations>
    <eOperations name="createCartesianPolygon" eType="#//CartesianPolygon">
      <eParameters name="v1" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
      <eParameters name="v2" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
      <eParameters name="v3" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eOperations name="createCartesianPositionCoordinates" eType="#//CartesianPositionCoordinates">
      <eParameters name="coordinates" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eOperations name="createCartesianOrientationCoordinates" eType="#//CartesianOrientationCoordinates">
      <eParameters name="coordinates" eType="#//CartesianOrientationCoordinates"/>
    </eOperations>
    <eOperations name="createCartesianCoordinatesMesh" eType="#//CartesianCoordinatesMesh">
      <eParameters name="cartesianCoordinatesMesh" eType="#//CartesianCoordinatesMesh"/>
    </eOperations>
    <eOperations name="createCartesianTriangle" eType="#//CartesianTriangle">
      <eParameters name="v1" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
      <eParameters name="v2" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
      <eParameters name="v3" lowerBound="1" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eOperations name="createCartesianTriangle" eType="#//CartesianTriangle">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CartesianPolygon"/>
      </eTypeParameters>
      <eParameters name="polygon">
        <eGenericType eTypeParameter="#//Data3dFacade/createCartesianTriangle.1/T"/>
      </eParameters>
    </eOperations>
    <eOperations name="applyTransform" eType="#//CartesianCoordinatesSet">
      <eParameters name="points" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="createCartesianCoordinatesMesh" eType="#//CartesianCoordinatesMesh">
      <eParameters name="polygons">
        <eGenericType eClassifier="#//List">
          <eTypeArguments eClassifier="#//CartesianPolygon"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="createCartesianTriangularMesh" eType="#//CartesianTriangularMesh">
      <eParameters name="polygons">
        <eGenericType eClassifier="#//List">
          <eTypeArguments eClassifier="#//CartesianTriangle"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="applyTransform">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
        <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      </eGenericType>
      <eParameters name="points">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
          <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
        </eGenericType>
      </eParameters>
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="applyTransform" eType="#//CartesianTriangularMesh">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="applyTransformInt" eType="#//CartesianTriangularMesh">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="applyTransform" eType="#//NormalPointCloud">
      <eParameters name="points" eType="#//NormalPointCloud"/>
      <eParameters name="trMatrix" eType="#//Matrix4d"/>
    </eOperations>
    <eOperations name="createCartesianCoordinatesMesh" lowerBound="1" eType="#//CartesianCoordinatesMesh">
      <eParameters name="cartesianTriangularMesh" eType="#//CartesianTriangularMesh"/>
    </eOperations>
    <eOperations name="createCartesianTriangularMesh" eType="#//CartesianTriangularMesh">
      <eParameters name="cartesianCoordinatesMesh" eType="#//CartesianTriangularMesh"/>
    </eOperations>
    <eOperations name="updateCartesianCoordinatesSet">
      <eParameters name="cartesianCoordinatesSet" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="xyzData" eType="#//DoubleArrayOfArray"/>
    </eOperations>
    <eOperations name="createPointNormalLocator" eType="#//PointNormalLocator">
      <eParameters name="input" eType="#//NormalPointCloud"/>
    </eOperations>
    <eOperations name="createDigitalElevationMap" eType="#//DigitalElevationMap">
      <eParameters name="coordinatesSet" eType="#//CartesianCoordinatesSet"/>
    </eOperations>
    <eOperations name="concatenateTriangularMeshes" eType="#//CartesianTriangularMesh">
      <eParameters name="listOfTriangularMeshes" lowerBound="1" upperBound="-1" eType="#//CartesianTriangularMesh"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data3DIO">
    <eOperations name="saveTriangularMesh" eExceptions="#//IOException">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
      <eParameters name="file" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="loadTriangularMesh" eType="#//CartesianTriangularMesh" eExceptions="#//IOException">
      <eParameters name="file" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="saveTriangularMesh" eExceptions="#//IOException">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
      <eParameters name="output" eType="#//OutputStream"/>
    </eOperations>
    <eOperations name="loadTriangularMesh" eType="#//CartesianTriangularMesh" eExceptions="#//IOException">
      <eParameters name="input" eType="#//InputStream"/>
    </eOperations>
    <eOperations name="loadTriangularMeshFromASCIIAsNormalPointCloud" eType="#//NormalPointCloud"
        eExceptions="#//IOException">
      <eParameters name="filePrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="loadTriangularMeshFromASCII" eType="#//CartesianTriangularMesh"
        eExceptions="#//IOException">
      <eParameters name="filePrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="saveTriangularMeshAsASCII" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
      <eParameters name="filePrefix" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="loadXYZ" eType="#//CartesianCoordinatesSet" eExceptions="#//IOException">
      <eParameters name="fileName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="loadTriangularMeshFromTriXYZ" eType="#//CartesianTriangularMesh"
        eExceptions="#//IOException">
      <eParameters name="triFileName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="xyzFileName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="saveCoordinatesSetToXYZ" eExceptions="#//IOException">
      <eParameters name="coordinatesSet" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="saveCoordinatesSetToXYZ" eExceptions="#//IOException">
      <eParameters name="coordinatesSet" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="file" eType="#//OutputStream"/>
    </eOperations>
    <eOperations name="saveCoordinatesSetToCSV" eExceptions="#//IOException">
      <eParameters name="coordinatesSet" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="file" eType="#//OutputStream"/>
    </eOperations>
    <eOperations name="saveCoordinatesSetToCSV" eExceptions="#//IOException">
      <eParameters name="coordinatesSet" eType="#//CartesianCoordinatesSet"/>
      <eParameters name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointLocator">
    <eOperations name="findClosestPoint" eType="#//CartesianPositionCoordinates">
      <eParameters name="point" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eOperations name="findPointsWithinRadius" upperBound="-1" eType="#//CartesianPositionCoordinates">
      <eParameters name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eParameters name="point" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
        <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data3DUtils">
    <eOperations name="computeNormals" upperBound="-1" eType="#//Vector3d">
      <eParameters name="mesh" eType="#//CartesianTriangularMesh"/>
    </eOperations>
    <eOperations name="computeCentroid" eType="#//CartesianPositionCoordinates">
      <eParameters name="points" eType="#//CartesianCoordinatesSet"/>
    </eOperations>
    <eOperations name="computeMinMaxValues">
      <eParameters name="min" eType="#//Point3d"/>
      <eParameters name="max" eType="#//Point3d"/>
      <eParameters name="data" eType="#//CartesianCoordinatesSet"/>
    </eOperations>
    <eOperations name="computeCurvatureChange" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble">
      <eParameters name="pointLocator" eType="#//PointLocator"/>
      <eParameters name="centerPoint" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="computeCurvatureChange" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble">
      <eParameters name="pointLocator" eType="#//VecmathPointLocator"/>
      <eParameters name="centerPoint" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    </eOperations>
    <eOperations name="extrude" eType="#//CartesianTriangularMesh">
      <eParameters name="profilePoints">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
          <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
        </eGenericType>
      </eParameters>
      <eParameters name="extrusionAxis" eType="#//CartesianAxis"/>
      <eParameters name="extrusionWidth" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="closeMesh" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CartesianAxis">
    <eLiterals name="X"/>
    <eLiterals name="Y" value="1"/>
    <eLiterals name="Z" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CartesianPlane">
    <eLiterals name="XY"/>
    <eLiterals name="XZ" value="1"/>
    <eLiterals name="YZ" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalPointCloud">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
        <eTypeArguments eClassifier="#//Point3d"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="normals">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
        <eTypeArguments eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VecmathPointLocator" abstract="true"
      interface="true">
    <eOperations name="findClosestPoint" eType="#//Point3d">
      <eParameters name="point" eType="#//Point3d"/>
    </eOperations>
    <eOperations name="findPointsWithinRadius" upperBound="-1" eType="#//Point3d">
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="point" eType="#//Point3d"/>
    </eOperations>
    <eOperations name="findClosestPointId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt">
      <eParameters name="point" eType="#//Point3d"/>
    </eOperations>
    <eOperations name="findPointIdsWithinRadius" eType="#//IntArray">
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="point" eType="#//Point3d"/>
    </eOperations>
    <eOperations name="findClosestNPoints" upperBound="-1" eType="#//Point3d">
      <eParameters name="referencePoint" eType="#//Point3d"/>
      <eParameters name="n" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="findClosestNPointIds" eType="#//IntArray">
      <eParameters name="referencePoint" eType="#//Point3d"/>
      <eParameters name="n" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" defaultValueLiteral="">
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
        <eTypeArguments eClassifier="#//Point3d"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VecmathKdTreePointLocator" eSuperTypes="#//VecmathPointLocator"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeshLocaliser">
    <eOperations name="localise" eType="#//Matrix4d" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Localise a floating mesh with respect to a fixed mesh. The transform returned is the transform between the floating mesh and the origin (i.e. a revised version of the floatingMeshTransformEstimate)."/>
      </eAnnotations>
      <eParameters name="fixedMesh" eType="#//CartesianTriangularMesh">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The mesh that is considered to be fixed."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="fixedMeshTransform" eType="#//Matrix4d">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The transform that connect the fixed mesh to the origin."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="floatingMesh" eType="#//CartesianTriangularMesh">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The mesh that is considered to be floating. Its position will be modified to align it with the fixed mesh."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="floatingMeshTransformEstimate" eType="#//Matrix4d">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The transform estimate that connect the floating mesh to the origin."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointNormalLocator">
    <eOperations name="findClosestPoint" eType="#//GVector">
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eOperations name="findPointsWithinRadius" upperBound="-1" eType="#//GVector">
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eOperations name="findClosestNPoints" upperBound="-1" eType="#//GVector">
      <eParameters name="n" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eOperations name="findClosestPointId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt">
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eOperations name="findPointIdsWithinRadius" eType="#//IntArray">
      <eParameters name="radius" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eOperations name="findClosestNPointIds" eType="#//IntArray">
      <eParameters name="n" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="point" eType="#//Point3d"/>
      <eParameters name="normal" eType="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//Vector3d"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSet" eType="#//NormalPointCloud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelaunayMesher" eSuperTypes="#//CartesianPositionCoordinatesMesher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tolerance" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.75"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boundingTriangulation"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meshingPlane" eType="#//MESHING_PLANE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalElevationMapMesher">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//DigitalElevationMap"/>
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalElevationMapSampler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetResolution" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//DigitalElevationMap"/>
      <eTypeArguments eClassifier="#//DigitalElevationMap"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriangularMeshNormalsCalculator">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriangularMesh2NormalPointCloud">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
      <eTypeArguments eClassifier="#//NormalPointCloud"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MESHING_PLANE">
    <eLiterals name="XY"/>
    <eLiterals name="YZ" value="1"/>
    <eLiterals name="XZ" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointsRangeGager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minX" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxX" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minY" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxY" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minZ" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxZ" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniquePointsFilter">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriangleEdgeLenghtTriangularMeshFilter">
    <eOperations name="filter" eType="#//CartesianTriangularMesh">
      <eParameters name="input" eType="#//CartesianTriangularMesh"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumRange" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumEdgeLenght" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutlierFilter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDistance" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RasterPointCloud">
    <eOperations name="getPoint" eType="#//CartesianPositionCoordinates">
      <eParameters name="row" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="column" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eOperations>
    <eOperations name="setPoint">
      <eParameters name="row" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="column" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
      <eParameters name="point" eType="#//CartesianPositionCoordinates"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rows" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columns" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RasterPointCloudToCartesianCoordinatesSet">
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//RasterPointCloud"/>
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeshSmoother" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfIterations" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
      <eTypeArguments eClassifier="#//CartesianTriangularMesh"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VoxelBased3DPointCloudResampler">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This processor subsamples a point cloud using a voxel approach based on an implementation of J. Bakambu from MDA."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolutionX" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Voxel size along the X axis."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolutionY" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Voxel size along the Y axis."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolutionZ" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="0.05">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Voxel size along the Z axis."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumNumberOfPointPerVoxel"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minimum number of point in every voxel."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tileResolution" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        defaultValueLiteral="5.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Size of the tiling to be used to process large data set. This is done to avoid memory problem."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
      <eTypeArguments eClassifier="#//CartesianCoordinatesSet"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RigidBodyPoseTracker">
    <eOperations name="computeTransformation" eType="#//Point3d" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This method computes the 3D rigid body transformation between two 3D data sets. First, the rotation matrix is computed using the Singular Values Decomposition (SVD) approach. Then, translation composent is computed. Finally, rotation and translation components are packed into an homogenous 4x4 matrix. Note : at least 3 markers are required to solve the 3D pose. If more than 3 markers are specified, the best fit (minimizing the root meaning squarre error) will be found."/>
      </eAnnotations>
      <eParameters name="markerPositionsToTrack" upperBound="-1" eType="#//PositionMarker">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="markerPositionsToTrack is a CartesianCoordinatesSet which represents the position of every marker with respect to the fixed frame."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="addPositionMarkers" eExceptions="ecore:EDataType platform:/plugin/ca.gc.space.mrt.common.processors/model/processors.ecore#//Exception">
      <eParameters name="marker" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
          <eTypeArguments eClassifier="#//PositionMarker"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="removePositionMarkers">
      <eParameters name="markers" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//List">
          <eTypeArguments eClassifier="#//PositionMarker"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionMarkersAtOrigin"
        upperBound="-1" eType="#//PositionMarker" changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionMarker" eSuperTypes="#//CartesianPositionCoordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="InputStream" instanceClassName="java.io.InputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOException" instanceClassName="java.io.IOException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="OutputStream" instanceClassName="java.io.OutputStream"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Matrix4d" instanceClassName="javax.vecmath.Matrix4d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Vector3d" instanceClassName="javax.vecmath.Vector3d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Point3d" instanceClassName="javax.vecmath.Point3d"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DoubleArrayOfArray" instanceClassName="double[][]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IntArray" instanceClassName="int[]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="GVector" instanceClassName="javax.vecmath.GVector"/>
  <eClassifiers xsi:type="ecore:EClass" name="CubeSamplingShape">
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//CartesianPolygon"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeJustTouching" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corner1" eType="#//CartesianPositionCoordinates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corner2" eType="#//CartesianPositionCoordinates"/>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//CoordinatesSamplingShape">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass platform:/plugin/org.eclipse.symphony.common.geometry.data/model/geometrydata.ecore#//PolygonSamplingShape">
      <eTypeArguments eClassifier="#//CartesianPositionCoordinates"/>
      <eTypeArguments eTypeParameter="#//CubeSamplingShape/PolygonType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CartesianCoordinatesSetExtent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMin" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xMax" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMin" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yMax" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zMin" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zMax" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimension" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimension" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zDimension" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
