/**
 *
 */
package org.eclipse.symphony.common.images.validation;

import java.awt.image.BufferedImage;

/**
 * A sample validator interface for {@link org.eclipse.symphony.common.images.EImage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EImageValidator {
	boolean validate();

	boolean validateImageContent(BufferedImage value);
}
