/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.common.math.validation;


/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.common.math.Matrix4x4}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Matrix4x4Validator {
	boolean validate();

	boolean validateM00(double value);
	boolean validateM01(double value);
	boolean validateM02(double value);
	boolean validateM03(double value);
	boolean validateM10(double value);
	boolean validateM11(double value);
	boolean validateM12(double value);
	boolean validateM13(double value);
	boolean validateM20(double value);
	boolean validateM21(double value);
	boolean validateM22(double value);
	boolean validateM23(double value);
	boolean validateM30(double value);
	boolean validateM31(double value);
	boolean validateM32(double value);
	boolean validateM33(double value);
}
