<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data" nsURI="http:///org/eclipse/symphony/common/geometry/data/model/geometrydata.ecore"
    nsPrefix="org.eclipse.symphony.common.geometry">
  <eClassifiers xsi:type="ecore:EClass" name="Coordinates"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinatesSet">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" ordered="false"
        upperBound="-1" containment="true" resolveProxies="false">
      <eGenericType eTypeParameter="#//CoordinatesSet/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="normals" transient="true">
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//Vector3d"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" ordered="false"
        upperBound="-1" resolveProxies="false">
      <eGenericType eTypeParameter="#//Polygon/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh">
    <eTypeParameters name="CoordinatesType">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//Polygon">
        <eTypeArguments eTypeParameter="#//Mesh/CoordinatesType"/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="getPolygonNeighbours" upperBound="-1">
      <eGenericType eTypeParameter="#//Mesh/PolygonType"/>
      <eParameters name="polygon">
        <eGenericType eTypeParameter="#//Mesh/PolygonType"/>
      </eParameters>
    </eOperations>
    <eOperations name="getPointNeighbours" upperBound="-1">
      <eGenericType eTypeParameter="#//Mesh/CoordinatesType"/>
      <eParameters name="point">
        <eGenericType eTypeParameter="#//Mesh/CoordinatesType"/>
      </eParameters>
    </eOperations>
    <eOperations name="getPolygonsSharingPoint" upperBound="-1">
      <eGenericType eTypeParameter="#//Mesh/PolygonType"/>
      <eParameters name="point">
        <eGenericType eTypeParameter="#//Mesh/CoordinatesType"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="polygons" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Mesh/PolygonType"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//CoordinatesSet">
      <eTypeArguments eTypeParameter="#//Mesh/CoordinatesType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SamplingShape" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinatesSamplingShape" abstract="true"
      interface="true" eSuperTypes="#//SamplingShape">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eOperations name="isInside" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="point">
        <eGenericType eTypeParameter="#//CoordinatesSamplingShape/T"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolygonSamplingShape" abstract="true"
      interface="true" eSuperTypes="#//SamplingShape">
    <eTypeParameters name="CoordinatesType">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//Polygon">
        <eTypeArguments eTypeParameter="#//PolygonSamplingShape/CoordinatesType"/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="isPolygonInside" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="polygon">
        <eGenericType eTypeParameter="#//PolygonSamplingShape/PolygonType"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoordinatesSetShapesSampler">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinatesSamplingShapes"
        upperBound="-1">
      <eGenericType eClassifier="#//CoordinatesSamplingShape">
        <eTypeArguments eTypeParameter="#//CoordinatesSetShapesSampler/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shapeSamplingMode" lowerBound="1"
        eType="#//ShapeSamplingMode" defaultValueLiteral="UNION"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//CoordinatesSet">
        <eTypeArguments eTypeParameter="#//CoordinatesSetShapesSampler/T"/>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//CoordinatesSet">
        <eTypeArguments eTypeParameter="#//CoordinatesSetShapesSampler/T"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeshCoordinatesShapesSampler" abstract="true">
    <eTypeParameters name="CoordinatesType">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//Polygon">
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/CoordinatesType"/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinatesSamplingShapes"
        upperBound="-1">
      <eGenericType eClassifier="#//CoordinatesSamplingShape">
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/CoordinatesType"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shapeSamplingMode" lowerBound="1"
        eType="#//ShapeSamplingMode" defaultValueLiteral="UNION"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="polygonSamplingMode" lowerBound="1"
        eType="#//PolygonSamplingMode" defaultValueLiteral="AT_LEAST_ONE_VERTEX"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//Mesh">
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/CoordinatesType"/>
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/PolygonType"/>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//Mesh">
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/CoordinatesType"/>
        <eTypeArguments eTypeParameter="#//MeshCoordinatesShapesSampler/PolygonType"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeshPolygonShapesSampler" abstract="true">
    <eTypeParameters name="CoordinatesType">
      <eBounds eClassifier="#//Coordinates"/>
    </eTypeParameters>
    <eTypeParameters name="PolygonType">
      <eBounds eClassifier="#//Polygon">
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/CoordinatesType"/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="polygonSamplingShapes"
        upperBound="-1">
      <eGenericType eClassifier="#//PolygonSamplingShape">
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/CoordinatesType"/>
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/PolygonType"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shapeSamplingMode" lowerBound="1"
        eType="#//ShapeSamplingMode" defaultValueLiteral="UNION"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.symphony.common.processors/model/processors.ecore#//Processor">
      <eTypeArguments eClassifier="#//Mesh">
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/CoordinatesType"/>
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/PolygonType"/>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//Mesh">
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/CoordinatesType"/>
        <eTypeArguments eTypeParameter="#//MeshPolygonShapesSampler/PolygonType"/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ShapeSamplingMode">
    <eLiterals name="UNION"/>
    <eLiterals name="INTERSECTION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PolygonSamplingMode">
    <eLiterals name="ALL_VERTEX"/>
    <eLiterals name="AT_LEAST_ONE_VERTEX" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Vector3d" instanceClassName="javax.vecmath.Vector3d"/>
</ecore:EPackage>
