<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="processors" nsURI="http:///ca/gc/space/mrt/common/processors/model/processors.ecore"
    nsPrefix="ca.gc.space.mrt.common">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="ca.gc.space.mrt.common"/>
    <details key="copyrightText" value="Canadian Space Agency 2007."/>
    <details key="importerID" value="org.eclipse.emf.importer.ecore"/>
    <details key="complianceLevel" value="5.0"/>
    <details key="operationReflection" value="false"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Monitorable" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represent a object for which operation progress can be reported."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progressMonitor" unique="false"
        eType="#//IProgressMonitor" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IProgressMonitor" instanceClassName="org.eclipse.core.runtime.IProgressMonitor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Processor" abstract="true" eSuperTypes="#//Monitorable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines an object that can process an input to get an output."/>
    </eAnnotations>
    <eTypeParameters name="I"/>
    <eTypeParameters name="O"/>
    <eOperations name="process" unique="false" eExceptions="#//Exception">
      <eGenericType eTypeParameter="#//Processor/O"/>
      <eParameters name="input" unique="false">
        <eGenericType eTypeParameter="#//Processor/I"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" unique="false" transient="true">
      <eGenericType eTypeParameter="#//Processor/I"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" unique="false"
        transient="true">
      <eGenericType eTypeParameter="#//Processor/O"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessorsChain">
    <eTypeParameters name="I"/>
    <eTypeParameters name="O"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intermediateResult" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningProcessor" lowerBound="1">
      <eGenericType eClassifier="#//Processor">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processors" upperBound="-1">
      <eGenericType eClassifier="#//Processor">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Processor">
      <eTypeArguments eTypeParameter="#//ProcessorsChain/I"/>
      <eTypeArguments eTypeParameter="#//ProcessorsChain/O"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobProcessorsChain">
    <eTypeParameters name="I"/>
    <eTypeParameters name="O"/>
    <eGenericSuperTypes eClassifier="#//ProcessorsChain">
      <eTypeArguments eTypeParameter="#//JobProcessorsChain/I"/>
      <eTypeArguments eTypeParameter="#//JobProcessorsChain/O"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerboseProvider" abstract="true" interface="true">
    <eOperations name="printVerbose" unique="false">
      <eParameters name="message" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verbose" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
