/**
 *
 * $Id$
 */
package ca.gc.asc_csa.apogy.common.topology.addons.dynamics.validation;

import ca.gc.asc_csa.apogy.common.math.Matrix4x4;

import ca.gc.asc_csa.apogy.common.topology.addons.dynamics.AbstractCollisionGeometrySimulationProperties;
import ca.gc.asc_csa.apogy.common.topology.addons.dynamics.AbstractMaterial;
import ca.gc.asc_csa.apogy.common.topology.addons.dynamics.Geometry;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ca.gc.asc_csa.apogy.common.topology.addons.dynamics.CollisionGeometry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollisionGeometryValidator {
	boolean validate();

	boolean validateSimulationProperties(EList<AbstractCollisionGeometrySimulationProperties> value);
	boolean validateGeometry(Geometry value);
	boolean validateTransform(Matrix4x4 value);
	boolean validateMaterial(AbstractMaterial value);
	boolean validateDescription(String value);
	boolean validateGeometryId(String value);
}
