package ca.gc.asc_csa.eclipse.emf.ecore;

public class EcoreConstants 
{
	public static String CSA_ANNOTATION_PREFIX = "csa";
	public static String CSA_ANNOTATION_SEPARATOR = "_";
	
	public static String CSA_ENGINEERING_UNITS = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + "units";
	public static String CSA_UPDATE_RATE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + "rate";
	
	public static String CSA_MIN_LIMIT = "min";
	public static String CSA_MAX_LIMIT = "max";	
	public static String CSA_OCL = "ocl";
	public static String CSA_OCL_MESSAGE = "oclmsg";
	
	public static String CSA_WARNING_RANGE = "warning";
	public static String CSA_ALARM_RANGE = "alarm";	
	public static String CSA_OUTSIDE_RANGE = "outside";	
	
	
	// Min and Max range values.
	// Warning level
	public static String CSA_WARNING_MIN_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_WARNING_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MIN_LIMIT;
	public static String CSA_WARNING_MAX_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_WARNING_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MAX_LIMIT;

	// Alarm level
	public static String CSA_ALARM_MIN_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_ALARM_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MIN_LIMIT;
	public static String CSA_ALARM_MAX_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_ALARM_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MAX_LIMIT;

	// Outside Range level.
	public static String CSA_OUTSIDE_RANGE_MIN_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_OUTSIDE_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MIN_LIMIT;
	public static String CSA_OUTSIDE_RANGE_MAX_VALUE = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_OUTSIDE_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_MAX_LIMIT;
	
	// OCL Expression Constants.
	// Warning level
	public static String CSA_WARNING_OCL_EXPRESSION = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_WARNING_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_OCL;
	public static String CSA_WARNING_OCL_MSG = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_WARNING_RANGE +  CSA_ANNOTATION_SEPARATOR + CSA_OCL_MESSAGE;
	
	// Alarm level
	public static String CSA_ALARM_OCL_EXPRESSION = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_ALARM_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_OCL;
	public static String CSA_ALARM_OCL_MSG = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_ALARM_RANGE +  CSA_ANNOTATION_SEPARATOR + CSA_OCL_MESSAGE;
	
	// Outside Range level.
	public static String CSA_OUTSIDE_RANGE_OCL_EXPRESSION = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_OUTSIDE_RANGE + CSA_ANNOTATION_SEPARATOR + CSA_OCL;
	public static String CSA_OUTSIDE_RANGE_OCL_MSG = CSA_ANNOTATION_PREFIX + CSA_ANNOTATION_SEPARATOR + CSA_OUTSIDE_RANGE +  CSA_ANNOTATION_SEPARATOR + CSA_OCL_MESSAGE;
}
